[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
envy = "0.4.2"
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
websocket = "0.27.1"
