# Clones the repository which then begins with validating the Gradle Wrapper checksum,
# If the checksum completes, the script then sets up the JDK we need and begins compiling the software,
# Finally, If the compiled files have been pushed out to the "(something)/build/libs/" directory - It gets uploaded to GitHub.
# vim:ft=yaml:ts=2:sts=2:sw=2:et:

name: Build GoofyPlugin with Gradle
on:
  push:
    branches:
      - 1-21
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            extra-experimental-features = nix-command flakes

      - name: Run checks
        run: nix flake check --log-format bar-with-logs

      - name: Build 1.21 using Nix
        run: nix run --log-format bar-with-logs .#build21

      - name: Build 1.21.1 using Nix
        run: nix run --log-format bar-with-logs .#build21-1

      - name: Build 1.21.4 using Nix
        run: nix run --log-format bar-with-logs .#build21-4

      - name: Upload Fabric artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Fabric-Artifacts
          path: fabric/build/libs/
